---
title: "Model Testing"
author: "Pablo, Juan, Alejandro"
date: "2024-06-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(plotly)
library(dplyr)
library(zoo)
```



```{r}
load('Data.RData')
```




```{r}

AllStations = COMPLETE

opciones = c("AvenidaFrancia", "Centre", "MoliDelSol",
             "PistaDeSilla", "UPV", "Olivereta"
             , "Puerto" , "AllStations")
```




# GRÁFICOS EXPLORATORIOS

```{r}
graficosPMporDia = list()
graficosPMporDiaInterpolacion = list()
graficosPMporDiaMedia = list()
```



```{r}

for (opcion in opciones) {


  c = get(opcion)
  
  datos_agrupados = c %>%
    group_by(FECHA) %>%
    summarise(total = mean(PM2.5))

  
  datos_agrupados$Interpolation <- na.approx(datos_agrupados$total, na.rm = FALSE)
  
  
  data_imputados = datos_agrupados[is.na(datos_agrupados$total), ]
  
  media_total <- mean(datos_agrupados$total, na.rm = TRUE)
  
  
data_imputados$Media = media_total
  
  
  
  
  
  
plot <- plot_ly(data = datos_agrupados, x = ~FECHA, y = ~total, name = 'Original Values') %>% add_lines() %>%
  layout(showlegend = TRUE, title = paste("2023 Temporal Graph of station", opcion),
         xaxis = list(title = "Date of 2023"), yaxis = list(title = "PM2.5")) 


graficosPMporDia[[opcion]] = plot
  
  
if (nrow(data_imputados) > 0 ){
plot2 <- plot %>% add_trace(data = data_imputados, x = ~FECHA, y = ~Interpolation, 
                           type = 'scatter', mode = 'markers',
                           marker = list(color = 'red', size = 5),
                           name = 'Interpolation Imputation')



plot3 = plot %>% add_trace(data = data_imputados, x = ~FECHA, y = ~Media, 
                           type = 'scatter', mode = 'markers',
                           marker = list(color = 'green', size = 5),
                           name = 'Mean Imputation')

}


graficosPMporDiaInterpolacion[[opcion]] = plot2


graficosPMporDiaMedia[[opcion]] = plot3
  

}




```





# Gráficos de partículas por horas

```{r}
graficosPMporHora <- list()

```

```{r}
library(ggplot2)
library(plotly)
library(dplyr)

for (opcion in opciones){
  
  c = get(opcion)
          
  datos_limpios <- c %>%
  filter(!is.na(PM2.5)) %>% filter(!is.na(HORA)) %>%
  group_by(HORA) %>%
  summarise(total = mean(PM2.5))
  
  
plot <- plot_ly(datos_limpios, x = ~HORA, y = ~total, type = 'scatter', mode = 'lines', line = list(color = 'blue')) %>%
  layout(title = paste('Temporal Graph of station', opcion,'grouped by hour of the day'),
         xaxis = list(title = 'Hour of the day' , range = c(0,24)),
         yaxis = list(title = 'PM2.5' , range = c(0, 15)),
         showlegend = FALSE)
  
  graficosPMporHora[[opcion]] =plot
  
  
}


```



```{r}
graficosPMporHora$AllStations
```



```{r}
COMPLETES = AllStations %>% slice(1:1000)
plot_ly(COMPLETES , x = ~CO, y = ~NO , type = 'scatter', mode = 'markers')
```




```{r}
save (graficosPMporHora, graficosPMporDia,graficosPMporDiaMedia , graficosPMporDiaInterpolacion, file = 'PreRenderedGraphs.RData')
```







