---
title: "Interface"
author: "Pablo, Juan, Alejandro"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(shinydashboard)
library(leaflet)
library(DT)
library(plotly)
library(dplyr)
```



```{r}
load('Data.RData')
```



# Pre-Rendered Graphs

Can be seen with more detail in our GitHub - ExploratoryAnalysis


```{r}
load('PreRenderedGraphs.RData')
```



## Options from selection parts
```{r}
opciones = c("AvenidaFrancia", "Centre", "MoliDelSol",
             "PistaDeSilla", "UPV", "Olivereta"
             , "Puerto", "AllStations")

sources= c("AvFrancia", "Centro", "Moli", "LlitAntic",
             "PistaSilla", "UPV", "Olivereta"
             , "Puerto")

variables = c("PM2.5" , "SO2" , "NO" , "NO2" , "NOx" , "O3" , "CO")


missingdatamethods = c('None' , 'Mean' , 'Interpolation')


variablesMapa = c("PM2.5" , "NO")

```


## Slice of All Stations

```{r}

set.seed(123)
COMPLETESLICE = na.omit(AllStations) %>% sample_n(size = 1000)
```




```{r}
dataMapa = AllStations %>% group_by(HORA, source)%>%
  summarise(totalPM = mean(PM2.5, na.rm = TRUE) , totalNO = mean(NO, na.rm = TRUE))


dataMapa$lng =  rep(c(-0.3426899, -0.37648469, -0.32894501 , -0.40855865,  -0.40603766,-0.37665323 , -0.32321741 , -0.3374074), 24)

dataMapa$lat = rep(c(39.45750439, 39.47071883, 39.45051894, 39.48113875,  39.46923859, 39.45806013,  39.45926486 , 39.47962193 ), 24)

dataMapa$label = rep(c("AvenidaFrancia", "Centre","LlicAnticTuria",  "MolidelSol", "Olivereta", "PistadeSilla" , "Puerto" , "UPV"), 24)


```
## MODEL

```{r}
modelo <- readRDS("modelo.rds")

# Función para realizar la predicción
predecir <- function(source, mes, dia, HORA) {
  # Crear un dataframe con las entradas del usuario
  nueva_data <- data.frame(
    source = source,
    mes = mes,
    dia = dia,
    HORA = HORA
  )
  
  # Realizar la predicción
  prediccion <- predict(modelo, nueva_data)
  
  return(prediccion)
}
```

# UI

```{r}
ui <- dashboardPage(
  dashboardHeader(title = "Air Pollution"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Data Exploratory Analysis", tabName = "exploratory", icon = icon("chart-bar")),
      menuItem("Data Science Model", tabName = "model", icon = icon("robot")),
      menuItem("Pollution Map", tabName = "map", icon = icon("map"))
    )
  ),
  
  
  dashboardBody(
    tabItems(

      tabItem(tabName = "exploratory",
h1("Data Exploratory Analysis"),
p('In this section you can see different distributions of our data
and play with them'),

h3('Scatter Plots'),
selectInput("variable1", "Select the first variable:",
choices = variables),
selectInput("variable2", "Select the second variable:",
choices = variables),
plotlyOutput("scatterPlot"),
p('Some variables, as they are similar chemical compounds, are high
correlated with each other'),

hr(),
hr(),

h1('Analysis per Station'),
selectInput("select", "Select one Station:", choices = opciones),
h3('Hour analysis'),
uiOutput("plot"),
p('In general terms, there is an increase in air particles at 8 and 9 oclock, and at 20 and 21 oclock. This may be due to increased transportation coinciding with work hours.'),

h3('Dealing with missing Data'),
p('We have some missing data from every station. To deal with it, we
prerent some different approaches'),
tags$ul(
  tags$li("Filling data with the total mean from the station"),
  tags$li("Filling data Interpolating from last and next day"),
),
selectInput("missingdata", "Select the missing data method:",
choices = missingdatamethods),
plotlyOutput("temporalPlotNA"),
p('Using the data as a temporal data, interpolation technique seems to
have better results')),
      

    tabItem(tabName = "model",
            h1("Data Science Model"),
            selectInput("source", "Select one Station:", choices = sources),
            sliderInput("month", "Select a month", min = 1, max = 12, value                         = 0),
            sliderInput("day", "Select a day", min = 1, max = 31, value               =               0),
            sliderInput("hour", "Select the hour of the day", min = 0, max = 23, value               = 0),
            actionButton("predict", "Predecir"),
            textOutput('prediction')
    ),
      
      
  tabItem(tabName = "map",
          h1("Pollution Map"),
          selectInput("mapSelect", "Select the metric to consider:",
          choices = variablesMapa),
          leafletOutput("mapa"),
          sliderInput("hora", "Select the hour of the day", min = 0, max = 23, value = 0, animate = animationOptions(interval = 1000)),
          p('It is surprising to see the outliers presented in NO at Olivereta Station between 6 and 9 am')
          

  )
  
  
    )
  )
)

```



# Server


```{r}
server <- function(input, output, session) {
  
  
  # Graph per Hour
  output$plot <- renderUI({
    req(input$select)
    plotlyOutput("selected_plot")
  })
  
  
  output$selected_plot <- renderPlotly({
    req(input$select)
    graficosPMporHora[[input$select]]
  })
  
  
  # Scatter Plot
  
  output$scatterPlot <- renderPlotly({
    req(input$variable1)
    req(input$variable2)
  
    a = COMPLETESLICE[,input$variable1]
    b = COMPLETESLICE[,input$variable2]
    
    plot_ly(
      data = COMPLETESLICE,
      x = a,
      y = b,
      type = 'scatter',
      mode = 'markers',
      text = ~paste('Date:', FECHA),
      hoverinfo = 'text')%>%
      layout(title = 'Scatter Plot with 1000 points',
         xaxis = list(title = input$variable1),
         yaxis = list(title = input$variable2))
    
    })
    
  
  # Temporal Graph
  
  output$temporalPlotNA <- renderPlotly({


req(input$missingdata) 
req(input$select)    
    
plot_selected <- switch(input$missingdata,
                        'None' = graficosPMporDia[[input$select]],
                        'Interpolation' =graficosPMporDiaInterpolacion[[input$select]],
                        'Mean' = graficosPMporDiaMedia[[input$select]])

plot_selected

  })
  
  
  
  
  
  # Model

    observeEvent(input$predict, {
    # Obtener las entradas del usuario
    source <- as.factor(input$source)
    mes <- as.factor(input$month)
    dia <- as.factor(input$day)
    HORA <- as.factor(input$hour)
    
    # Realizar la predicción
    prediccion <- predecir(source, mes, dia, HORA)
    
    # Mostrar la predicción en la interfaz de usuario
    output$prediction <- renderText({
      paste("Prediction of PM2.5 for these values is:", prediccion)
    })
  })
  


  

  
  
  # Map
  
  
  data_filtered <- reactive({
    dataMapa %>% filter(HORA == input$hora)
  })
  
  
  palPM <- colorNumeric(palette = "RdYlGn", domain = dataMapa$totalPM, reverse = TRUE)
  palNO <- colorNumeric(palette = "RdYlGn", domain = dataMapa$totalNO, reverse = TRUE)
    
    output$mapa <- renderLeaflet({
      
    if (input$mapSelect == 'PM2.5'){

    leaflet() %>%
      addTiles() %>%
      setView(lng = -0.36739, lat = 39.46975, zoom = 13) %>%
      addCircleMarkers(
        data = data_filtered(),
        lng = ~lng,
        lat = ~lat,
        label = ~label,
        radius = 20,
        color = "black",
        fillColor = ~palPM(totalPM),
        fillOpacity = 0.7, 
        weight = 1,
        popup = ~paste("PM2.5:", totalPM)
      )
} else {
    leaflet() %>%
      addTiles() %>%
      setView(lng = -0.36739, lat = 39.46975, zoom = 13) %>%
      addCircleMarkers(
        data = data_filtered(),
        lng = ~lng,
        lat = ~lat,
        label = ~label,
        radius = 20,
        color = "black",
        fillColor = ~palNO(totalNO),
        fillOpacity = 0.7,
        weight = 1,
        popup = ~paste("NO:", totalNO) )
}
      
  })
    

 
     
}


```


# Run


```{r}
shinyApp(ui = ui, server = server)
```


